### ISSUE TITLE
SSO login with Keycloak

### ISSUE THREAD

**Issue by sergloko** [cronicle-edge/cronicle-edge#163]
Hello. I'm trying to set up SSO via keycloak. But I get an error. Can you tell me how to integrate with Keycloak?

Here is my cronicle configuration:

```
 "oauth": {
    "enabled": true,
    "insecure": false,
    "client_id": "cronicle",
    "client_secret": "mykeyyyyyyyyyyyy",
    "redirect_uri": "https://MYDOMAIN/api/user/callback",
    "authorize_url": "https://MYDOMAIN/auth/realms/blk/protocol/openid-connect/auth",
    "token_url": "=https://MYDOMAIN/auth/realms/blk/protocol/openid-connect/token",
    "user_url": "=https://MYDOMAIN/auth/realms/blk/protocol/openid-connect/userinfo",
    "user_attribute": "preferred_username",
    "scope": "email openid profile"
  },
```
After entering the data into keycloak, I get an error

```
[1734461597.319][2024-12-17 23:53:17][cronicle-manager][1][WebServer][debug][6][Invoking handler for request: GET /api/user/callback: API][{"id":"r416"}]

[1734461597.319][2024-12-17 23:53:17][cronicle-manager][1][API][debug][6][Handling API request: GET /api/user/callback?state=2da499baa8bdada6.Home&session_state=0e1709f9-dbdb-43b8-805e-d57d569035d0&iss=https%3A%2F%2FMYDOMAIN%2Fauth%2Frealms%2Fblk&code=f9f53313-7d6c-4b8d-bfed-678004ebcfb3.0e1709f9-dbdb-43b8-805e-d57d569035d0.e4e00d54-6959-49a6-a5e8-b2aec5b624f4][]

[1734461597.319][2024-12-17 23:53:17][cronicle-manager][1][API][debug][9][API Params][{}]

[1734461597.319][2024-12-17 23:53:17][cronicle-manager][1][API][debug][9][Activating namespaced API handler: user/api_callback for URI: /api/user/callback][]

[1734461597.319][2024-12-17 23:53:17][cronicle-manager][1][User][debug][3][Requesting oauth token from:][=https://MYDOMAIN/auth/realms/blk/protocol/openid-connect/token]

[1734461597.322][2024-12-17 23:53:17][cronicle-manager][1][User][error][3][oauth failed][AggregateError]

[1734461597.322][2024-12-17 23:53:17][cronicle-manager][1][User][error][login][oath failed][]

[1734461597.322][2024-12-17 23:53:17][cronicle-manager][1][WebServer][debug][10][API Response JSON:][{"code":"login","description":"oath failed"}]

[1734461597.323][2024-12-17 23:53:17][cronicle-manager][1][WebServer][debug][9][Compressed text output with gzip: 45 bytes down to: 64 bytes][]

[1734461597.323][2024-12-17 23:53:17][cronicle-manager][1][WebServer][debug][9][Sending compressed HTTP response with gzip: 200 OK][{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Server":"Cronicle 1.0","Content-Length":64,"Content-Encoding":"gzip"}]

[1734461597.324][2024-12-17 23:53:17][cronicle-manager][1][WebServer][debug][9][Request complete][]

[1734461597.324][2024-12-17 23:53:17][cronicle-manager][1][WebServer][debug][9][Response finished writing to socket][{"id":"r416"}]
```

Keycloak is configured as follows:
[Keycloak_client_cronicle.json](https://github.com/user-attachments/files/18170372/Keycloak_client_cronicle.json)

~~~
{
  "clientId": "cronicle",
  "name": "cronicle",
  "description": "",
  "rootUrl": "",
  "adminUrl": "",
  "baseUrl": "",
  "surrogateAuthRequired": false,
  "enabled": true,
  "alwaysDisplayInConsole": false,
  "clientAuthenticatorType": "client-secret",
  "secret": "mysecrettttttt",
  "redirectUris": [
    "https://MYDOMAIN/api/user/callback"
  ],
  "webOrigins": [
    "*"
  ],
  "notBefore": 0,
  "bearerOnly": false,
  "consentRequired": false,
  "standardFlowEnabled": true,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": true,
  "serviceAccountsEnabled": true,
  "authorizationServicesEnabled": true,
  "publicClient": false,
  "frontchannelLogout": true,
  "protocol": "openid-connect",
  "attributes": {
    "oidc.ciba.grant.enabled": "false",
    "client.secret.creation.time": "1734460120",
    "backchannel.logout.session.required": "true",
    "display.on.consent.screen": "false",
    "oauth2.device.authorization.grant.enabled": "true",
    "use.jwks.url": "false",
    "backchannel.logout.revoke.offline.tokens": "false"
  },
  "authenticationFlowBindingOverrides": {},
  "fullScopeAllowed": true,
  "nodeReRegistrationTimeout": -1,
  "protocolMappers": [
    {
      "name": "Client Host",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usersessionmodel-note-mapper",
      "consentRequired": false,
      "config": {
        "user.session.note": "clientHost",
        "id.token.claim": "true",
        "introspection.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "clientHost",
        "jsonType.label": "String"
      }
    },
    {
      "name": "Client IP Address",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usersessionmodel-note-mapper",
      "consentRequired": false,
      "config": {
        "user.session.note": "clientAddress",
        "id.token.claim": "true",
        "introspection.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "clientAddress",
        "jsonType.label": "String"
      }
    },
    {
      "name": "Client ID",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usersessionmodel-note-mapper",
      "consentRequired": false,
      "config": {
        "user.session.note": "client_id",
        "id.token.claim": "true",
        "introspection.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "client_id",
        "jsonType.label": "String"
      }
    }
  ],
  "defaultClientScopes": [
    "web-origins",
    "acr",
    "openid",
    "roles",
    "profile",
    "section",
    "basic",
    "email"
  ],
  "optionalClientScopes": [
    "address",
    "phone",
    "offline_access",
    "microprofile-jwt"
  ],
  "access": {
    "view": true,
    "configure": true,
    "manage": true
  }
}
~~~
I will be grateful for your help and feedback. Thanks)

**Comment by mikeTWC1984** [comment]
Is that leading "=" is typo or it's in your configuration?
"=https://MYDOMAIN/auth/realms/blk/protocol/openid-connect/token"

**Comment by mikeTWC1984** [comment]
You probably need to remove "/auth" from urls. I tried latest keyclock docker image with this config, and it's working:
```json
	"oauth": {
		"enabled": true,
		"insecure": true,
		"client_id": "cronicle",
		"client_secret": "************",
		"redirect_uri": "http://localhost:3012/api/user/callback",
		"authorize_url": "http://localhost:8080/realms/master/protocol/openid-connect/auth",
		"token_url": "http://localhost:8080/realms/master/protocol/openid-connect/token",
		"user_url": "http://localhost:8080/realms/master/protocol/openid-connect/userinfo",
		"user_attribute": "preferred_username",
		"scope": "email openid profile"
	},
```

**Comment by sergloko** [comment]
Is it possible to use locations /api, /socket.io transfer to /cron? Otherwise, SSO with location/cron does not work.

**Comment by sergloko** [comment]
I guess I'll have to wait for this [PR](https://github.com/cronicle-edge/cronicle-edge/pull/122). Can you tell me how soon it is planned to be checked?

**Comment by mikeTWC1984** [comment]
Well, this feature was added recently. You can set it via base_path = /cron
See notes:
https://github.com/cronicle-edge/cronicle-edge/releases/tag/v1.10.1

**Comment by sergloko** [comment]
> Well, this feature was added recently. You can set it via base_path = /cron See notes: https://github.com/cronicle-edge/cronicle-edge/releases/tag/v1.10.1

Sorry. As I didn't notice it, I probably mistook it for base_app_url.

**Comment by sergloko** [comment]
I applied a variable and now I get the following.

When SSO is selected at the input. Does the /api/user/oauth page open? instead of /cronicle/api/user/oauth?

https://github.com/cronicle-edge/cronicle-edge/blob/5dc439d3448bf2033e8c6c16c3c976336e21c914/htdocs/js/pages/Login.class.js#L86-L96

**Comment by mikeTWC1984** [comment]
yeah, I guess need to add base_path to that URL. Base path is stored in app.config.base_path. Are you able to test it on your end?
```js
if(/^\/\w+$/.test(app.config.base_path)) { window.location.href = app.config.base_path + `/api/user/oauth?orig_location=${orig_location}` }
```

**Comment by mikeTWC1984** [comment]
I guess need also add this for callback api

**Comment by sergloko** [comment]
> I guess need also add this for callback api

Yes, the api does not work correctly with the callback either.

**Comment by sergloko** [comment]
> yeah, I guess need to add base_path to that URL. Base path is stored in app.config.base_path. Are you able to test it on your end?
> 
> ```js
> if(/^\/\w+$/.test(app.config.base_path)) { window.location.href = app.config.base_path + `/api/user/oauth?orig_location=${orig_location}` }
> ```

Yes, I will test it. Can you tell me where to apply the callback api?

**Comment by mikeTWC1984** [comment]
OK, in Login.class.js change line 95 to:
```js
			let base_path = /^\/\w+$/.test(app.config.base_path) ? app.config.base_path : '';
			window.location.href = `${base_path}/api/user/oauth?orig_location=${orig_location}`;
```

then it lib/user.js locate lines with "Set-Cookie", and replace / with /cron like this:
```js
					res.setHeader('Set-Cookie', `session_id=${session_id}; HttpOnly; Path=/cron/; Max-Age=10; Secure=True; SameSite=Strict`)
					res.writeHead(302, { Location: '/cron/#' + orig_location })
```

```js
args.response.setHeader('Set-Cookie', `session_id=; HttpOnly; Path=/cron/; Max-Age=0; Secure=True; SameSite=Strict`);
```

that seemed to fix the issue on my end. Also, update redirect_url in keycloack client setting to include /cron

**Comment by sergloko** [comment]
> OK, in Login.class.js change line 95 to:
> 
> ```js
> 			let base_path = /^\/\w+$/.test(app.config.base_path) ? app.config.base_path : '';
> 			window.location.href = `${base_path}/api/user/oauth?orig_location=${orig_location}`;
> ```
> 
> then it lib/user.js locate lines with "Set-Cookie", and replace / with /cron like this:
> 
> ```js
> 					res.setHeader('Set-Cookie', `session_id=${session_id}; HttpOnly; Path=/cron/; Max-Age=10; Secure=True; SameSite=Strict`)
> 					res.writeHead(302, { Location: '/cron/#' + orig_location })
> ```
> 
> ```js
> args.response.setHeader('Set-Cookie', `session_id=; HttpOnly; Path=/cron/; Max-Age=0; Secure=True; SameSite=Strict`);
> ```
> 
> that seemed to fix the issue on my end. Also, update redirect_url in keycloack client setting to include /cron

Oh, great! Now it's all working here.)

**Comment by VnUgE** [comment]
Hi, I just configured the latest main branch and also tried v1.11.3. I'm using Keycloak as well. I configured according to your guides and all seems well except my Cronicle client is not being authorized after Keycloak redirects back to Cronicle, then attempts to complete authentication. It sends me back to the login page. I can see that 
```
GET http://container01:8104/api/user/callback?=...
```

Responds with
```
HTTP/1.1 302 Found
Set-Cookie: session_id=<cookie_value>; HttpOnly; Path=/; Max-Age=10; Secure=True; SameSite=Strict
Location: /#Home
Date: Sun, 09 Feb 2025 18:27:57 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

However the client does not seem to complete the authentication. 

**If I manually set the cookie `session_id=<cookie_value>` and refresh the `/Home` page everything is fine.** 

**But** If I refresh the login page after setting the cookie manually this error occurs and the server process crashes and needs to be restarted 

```
[1739125648.765][2025-02-09 13:27:28][container01[2][User][debug][3][session_id is already set, redirecting user back][b13e7b41f8340cbeb2474750976a49e0f18f69ceb20a6ab9489e4ce840590ad5]
[1739125648.778][2025-02-09 13:27:28][container01][2][Cronicle][debug][1][Uncaught Exception: ReferenceError: res is not defined][ReferenceError: res is not defined     at __construct.api_oauth (/opt/cronicle/bin/cronicle.js:149:14906)     at __construct.handler (/opt/cronicle/bin/cronicle.js:85:5137)     at __construct.handleHTTPRequest (/opt/cronicle/bin/cronicle.js:70:43)     at __construct.filterHTTPRequest (/opt/cronicle/bin/cronicle.js:68:2392)     at __construct.parseHTTPRequest (/opt/cronicle/bin/cronicle.js:68:2105)     at /opt/cronicle/bin/cronicle.js:58:9799     at Object.process (/opt/cronicle/bin/cronicle.js:58:4036)     at /opt/cronicle/bin/cronicle.js:58:2465     at /opt/cronicle/bin/cronicle.js:56:19733     at node:internal/process/task_queues:140:7]
[1739125648.779][2025-02-09 13:27:28][container01][2][Error][error][crash][Emergency Shutdown: ReferenceError: res is not defined][]
[1739125648.779][2025-02-09 13:27:28][container01][2][Cronicle][debug][1][Emergency Shutdown: ReferenceError: res is not defined][]
curl: (2) no URL specified
curl: try 'curl --help' or 'curl --manual' for more information
node:child_process:965
    throw err;
    ^

Error: Command failed: curl -X POST -H 'Content-Type: application/json' -d '{"text":"cronicle: Emergency Shutdown (uncaught exception)"}'
curl: (2) no URL specified
curl: try 'curl --help' or 'curl --manual' for more information

    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at __construct.emergencyShutdown (/opt/cronicle/bin/cronicle.js:230:9539)
    at EventEmitter.emit (node:events:530:35)
    at process.<anonymous> (/opt/cronicle/bin/cronicle.js:3:5032)
    at process.emit (node:events:518:28)
    at process._fatalException (node:internal/process/execution:178:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 2,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(91) [Uint8Array] [
       99, 117, 114, 108,  58,  32,  40,  50,  41,  32, 110, 111,
       32,  85,  82,  76,  32, 115, 112, 101,  99, 105, 102, 105,
      101, 100,  10,  99, 117, 114, 108,  58,  32, 116, 114, 121,
       32,  39,  99, 117, 114, 108,  32,  45,  45, 104, 101, 108,
      112,  39,  32, 111, 114,  32,  39,  99, 117, 114, 108,  32,
       45,  45, 109,  97, 110, 117,  97, 108,  39,  32, 102, 111,
      114,  32, 109, 111, 114, 101,  32, 105, 110, 102, 111, 114,
      109,  97, 116, 105, 111, 110,  10
    ]
  ],
  pid: 44,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(91) [Uint8Array] [
     99, 117, 114, 108,  58,  32,  40,  50,  41,  32, 110, 111,
     32,  85,  82,  76,  32, 115, 112, 101,  99, 105, 102, 105,
    101, 100,  10,  99, 117, 114, 108,  58,  32, 116, 114, 121,
     32,  39,  99, 117, 114, 108,  32,  45,  45, 104, 101, 108,
    112,  39,  32, 111, 114,  32,  39,  99, 117, 114, 108,  32,
     45,  45, 109,  97, 110, 117,  97, 108,  39,  32, 102, 111,
    114,  32, 109, 111, 114, 101,  32, 105, 110, 102, 111, 114,
    109,  97, 116, 105, 111, 110,  10
  ]
}

Node.js v20.11.1
ERROR: Please stop Cronicle before running this script.
removing old pid file
[1739125650.668][2025-02-09 13:27:30][container01][2][Cronicle][debug][2][Cronicle v1.11.3 Starting Up][{"pid":2,"ppid":1,"node":"v20.11.1","arch":"x64","platform":"linux","argv":["/usr/bin/node","/opt/cronicle/bin/cronicle.js","--echo","--foreground","--manager","--color","0","--debug","0"],"execArgv":[]}]
```

I suspect I should upgrade to an https connection next to see if the cookie becomes set. Since this is not running on local host, I assume my browser is dropping the `session_id` cookie without telling me in the console log.

**Comment by mikeTWC1984** [comment]
OK, if session_id is set when you hit oauth api, it do some sanity check for that (to prevent generating new tokens), I noticed http response object is defined after that check. Just fixed that on main branch (thanks!)

Ok, now can you pull latest main branch, then try to login again, grep you logs with User.

The cookie generated for oauth is short-lived (expires in about 10 seconds or so). It's purpose is just to set session_id on localStorage object (same mechanism as normal user login). 

There is api enpoint for debugging sessions  /api/app/whoami, you can try to hit it right after login, so you can see cookies (but you also need to set config debug = true, you can do it in admin/config keys)

**Comment by VnUgE** [comment]
Okay. So it looks like the cookie is getting set, same as before like:
```
Set-Cookie: session_id=<value>; HttpOnly; Path=/; Max-Age=10; Secure=True; SameSite=Strict
```
With __HttpOnly__ flag set the front-end cant read that cookie, I'm not sure if that's intentional. If I manually copy the cookie value and set `session_id` in local storage, then all is good and the server doesn't crash. When I set the cookie value manually like before and refresh the page on `/Login` the server still crashes with the same issue. 

I do run many services on the same server so it has a lot of cookies set, but I made sure to open a new private window for this test and the same behavior exists with no other cookie's set. I made sure they don't conflict either. 

- Started container
- Opened a new private window
- Went to / -> /Login
- Clicked on SSO Login
- Authenticated with Keycloak (different server)
- Redirected back to /Login as usual
- Captured log:
```
podman-compose logs cronicle-edge | grep User

[1739205822.737][2025-02-10 11:43:42][container01.***][2][Cronicle][debug][3][Starting component: User][]
[1739205822.738][2025-02-10 11:43:42][container01.***][2][User][debug][3][User Manager starting up][]
[1739205828.72][2025-02-10 11:43:48][container01.***][2][User][error][session][Session has expired or is invalid.][]
[1739205831.007][2025-02-10 11:43:51][container01.***][2][User][debug][3][Requesting oauth token from:][https://internal01.***:8443/realms/***/protocol/openid-connect/token]
[1739205831.292][2025-02-10 11:43:51][container01.***][2][User][debug][3][oauth user info:][{"sub":"ae62dcc7-b322-4dbd-ab27-671d174930a1","email_verified":true,"name":"*** ***","preferred_username":"***@***","given_name":"***","family_name":"***","email":"***@***"}]
[1739205831.307][2025-02-10 11:43:51][container01.***][2][User][debug][6][Logging user in: ***@***: New Session ID: 9b05f95ad78f80ced5a9f5a6229bff82089ebf8d8d8415abc07ac10d6a328afc][{"id":"9b05f95ad78f80ced5a9f5a6229bff82089ebf8d8d8415abc07ac10d6a328afc","username":"***@***","ip":"25.83.220.99","useragent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","created":1739205831,"modified":1739205831,"expires":1741752000}]
[1739205831.311][2025-02-10 11:43:51][container01.***][2][User][debug][6][Successfully logged in][]
[1739205831.312][2025-02-10 11:43:51][container01.***][2][User][transaction][user_login][***@***][{"ip":"25.83.220.99","headers":{"host":"container01.***:8104","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","sec-gpc":"1","connection":"keep-alive","upgrade-insecure-requests":"1","via":"1.1 25.83.220.99","x-forwarded-for":"25.83.220.99","priority":"u=0, i","pragma":"no-cache","cache-control":"no-cache"}}]
[1739205832.114][2025-02-10 11:43:52][container01.***][2][User][error][session][Session has expired or is invalid.][]
```

**Comment by mikeTWC1984** [comment]
As you mentioned and based on logs when you get back from keycloak to /callback api, session is generated  successfully.
What callback do is getting you to original page requested (or Home) attaching that short-lived cookie.

Then when you get to original page, it runs "requireLogin" check. Basically it checks for session_id in localStorage and cookie, and if it valid it resumes user session.
https://github.com/cronicle-edge/cronicle-edge/blob/67ee40dd2550a9e275f36337d3a4d148df9af686/htdocs/js/pages/Base.class.js#L5

So I believe either you has no cookie, or it has some bad value.

Try do following:
Run cronicle in debug mode, by adding --debug flag, e.g.
 ```
 docker run --rm -p 3022:3012 -it ghcr.io/cronicle-edge/cronicle-edge:main manager --debug
```

This will enable /api/app/whoami endpoint and debug traces in browser dev tools.
So when in debug mod  - open browser dev console and watch messages it prints while you login
Also once ouath login is over - go to /api/app/whoami   (in browser), check what cookies you have
