### ISSUE TITLE
Script executes manual (clicking "run") but not on a schedule, throwing Transport http error

### ISSUE THREAD

**Issue by dreadedhamish** [cronicle-edge/cronicle-edge#164]
I post this first in the cronicle repo (https://github.com/jhuckaby/Cronicle/issues/836) , but jhuckaby didn't have any insights and suggested I cross-post here:

When running a script manually (clicking "run") script executes correctly, but when run on a schedule it throws a connection error:
```
Traceback (most recent call last):
  File "/home/hamish/Documents/Code/scrape-officehq-linux/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamish/Documents/Code/scrape-officehq-linux/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hamish/.pyenv/versions/3.11.9/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x779471b8e850>: Failed to resolve 'oauth2.googleapis.com' ([Errno -3] Temporary failure in name resolution)"))
Is there any difference when running using manual execution - "run" - vs. on a schedule?
```
Steps to reproduce the problem
This is a complex setup:
Using cronicle-edge
Add shell script to call python script
Python script has it's own enviromnent:
```
#!/bin/bash
export DISPLAY=:0

# Navigate to the project directory (replace with your actual project path)
cd /home/hamish/Documents/Code/scrape-officehq-linux/

# Run the Python script using Poetry
poetry run python selenium.py
Inside python script use gspread to make a connection to Google.
```
Your Setup
cronicle-edge 1.11.0
running native (no docker)

Operating system and version?
Manjaro Linux

Node.js version?
Node.js v22.9.0

Cronicle software version?
cronicle-edge 1.11.0

Are you using a multi-server setup, or just a single server?
Single server setup

Are you using the filesystem as back-end storage, or S3/Couchbase?
filesystem

Can you reproduce the crash consistently?
yes

**Comment by mikeTWC1984** [comment]
Based on logs you provided the error is in hostname resolution. Perhaps your DNS have some intermittent issues? Try run this job on schedule several times and see if it  sometime gets through.

Manual run vs scheduled are a bit different. First is launching job via API from your browser, but schedule is invoked internally in the engine. I can't really see what would affect context difference between manual and schedule. One thing you can check - wrap you job with another Worflow job. Workflow is also using same API to launch job as manual run. Put that Workflow job on schedule and see if it works or not.

One more thing I'd check is if you use some custom username or working directory for shell plugin.

**Comment by dreadedhamish** [comment]
> Based on logs you provided the error is in hostname resolution. Perhaps your DNS have some intermittent issues? Try run this job on schedule several times and see if it sometime gets through.
> 
> Manual run vs scheduled are a bit different. First is launching job via API from your browser, but schedule is invoked internally in the engine. I can't really see what would affect context difference between manual and schedule. One thing you can check - wrap you job with another Worflow job. Workflow is also using same API to launch job as manual run. Put that Workflow job on schedule and see if it works or not.
> 
> One more thing I'd check is if you use some custom username or working directory for shell plugin.

thanks - I'll have a play.

Initially i thought it was just a DNS issue, but for days it's been throwing that error 100% of the time when scheduled, but never when manually run.

**Comment by mikeTWC1984** [comment]
Can you add id and nslookup command to your bash script. Is there an diff if you run it from scheduler/manually?

```bash
#!/bin/bash
export DISPLAY=:0

id
nslookup oauth2.googleapis.com

# Navigate to the project directory (replace with your actual project path)
cd /home/hamish/Documents/Code/scrape-officehq-linux/

# Run the Python script using Poetry
poetry run python selenium.py
Inside python script use gspread to make a connection to Google.
```
