### ISSUE TITLE
Account creation from login screen fails with exception

### ISSUE THREAD

**Issue by tobyX** [cronicle-edge/cronicle-edge#22]
I tried to use the account creation from the login screen (I enabled free accounts in the config) but it fails with this exception:

```
[1646993665.523][2022-03-11 05:14:25][cronicle_manager][1][API][debug][6][Handling API request: GET /api/app/check_user_exists?username=test&cachebust=1646993660.814][]
[1646993680.072][2022-03-11 05:14:40][cronicle_manager][1][WebServer][debug][6][Invoking handler for request: POST /api/user/create: API][{"id":"r102"}]
[1646993680.073][2022-03-11 05:14:40][cronicle_manager][1][API][debug][6][Handling API request: POST /api/user/create][{}]
[1646993680.082][2022-03-11 05:14:40][cronicle_manager][1][Cronicle][debug][1][Uncaught Exception: Error: Storage has not completed startup.][Error: Storage has not completed startup.     at get (/opt/cronicle/node_modules/pixl-server-storage/storage.js:314:39)     at node:internal/util:360:7     at new Promise (<anonymous>)     at get (node:internal/util:346:12)     at constructor.api_create (/opt/cronicle/lib/user.js:101:
24)     at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:89:21)     at WebServer.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/lib/request.js:459:12)     at WebServer.filterHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/lib/request.js:339:36)     at IncomingMessage.<anonymous> (/opt/cronicle/node_modules/pixl-server-web/lib/request.js:312:11)     at IncomingMessage.emit (nod
e:events:532:35)]
[1646993680.082][2022-03-11 05:14:40][cronicle_manager][1][Error][error][crash][Emergency Shutdown: Error: Storage has not completed startup.][]
[1646993680.086][2022-03-11 05:14:40][cronicle_manager][1][Cronicle][debug][1][Emergency Shutdown: Error: Storage has not completed startup.][]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[1646993680.115][2022-03-11 05:14:40][cronicle_manager][1][Cronicle][debug][1][Uncaught Exception: Error: Command failed: curl -X POST -H 'Content-Type: application/json' -d '{"text":"cronicle: Emergency Shutdown (uncaught exception)"}'  curl: no URL specified! curl: try 'curl --help' or 'curl --manual' for more information ][Error: Command failed: curl -X POST -H 'Content-Type: application/json' -d '{"text":"cronicle: Emergency Shutdown (uncaught exception)"}'  curl: no URL specified! curl: try 'curl --help' or 'curl --manual' for more information      at checkExecSyncError (node:child_process:828:11)     at Object.execSync (node:child_process:902:15)     at constructor.emergencyShutdown (/opt/cronicle/lib/engine.js:1637:6)     at EventEmitter.emit (node:events:532:35)     at process.<anonymous> (/opt/cronicle/node_modules/uncatch/uncatch.js:25:11)     at process.emit (node:events:520:28)     at emit (node:internal/process/promises:133:20)     at processPromiseRejections (node:internal/process/promises:260:27)     at processTicksAndRejections (node:internal/process/task_queues:97:32)]
[1646993680.116][2022-03-11 05:14:40][cronicle_manager][1][Error][error][crash][Emergency Shutdown: Error: Command failed: curl -X POST -H 'Content-Type: application/json' -d '{"text":"cronicle: Emergency Shutdown (uncaught exception)"}'  curl: no URL specified! curl: try 'curl --help' or 'curl --manual' for more information ][]
[1646993680.117][2022-03-11 05:14:40][cronicle_manager][1][Cronicle][debug][1][Emergency Shutdown: Error: Command failed: curl -X POST -H 'Content-Type: application/json' -d '{"text":"cronicle: Emergency Shutdown (uncaught exception)"}'  curl: no URL specified! curl: try 'curl --help' or 'curl --manual' for more information ][]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
node:child_process:905
    throw err;
    ^

Error: Command failed: curl -X POST -H 'Content-Type: application/json' -d '{"text":"cronicle: Emergency Shutdown (uncaught exception)"}'
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at constructor.emergencyShutdown (/opt/cronicle/lib/engine.js:1637:6)
    at EventEmitter.emit (node:events:532:35)
    at process.<anonymous> (/opt/cronicle/node_modules/uncatch/uncatch.js:20:11)
    at process.emit (node:events:520:28)
    at process._fatalException (node:internal/process/execution:164:25) {
  status: 2,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(88) [Uint8Array] [
       99, 117, 114, 108,  58,  32, 110, 111,  32,  85, 82,  76,
       32, 115, 112, 101,  99, 105, 102, 105, 101, 100, 33,  10,
       99, 117, 114, 108,  58,  32, 116, 114, 121,  32, 39,  99,
      117, 114, 108,  32,  45,  45, 104, 101, 108, 112, 39,  32,
      111, 114,  32,  39,  99, 117, 114, 108,  32,  45, 45, 109,
       97, 110, 117,  97, 108,  39,  32, 102, 111, 114, 32, 109,
      111, 114, 101,  32, 105, 110, 102, 111, 114, 109, 97, 116,
      105, 111, 110,  10
    ]
  ],
  pid: 42,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(88) [Uint8Array] [
     99, 117, 114, 108,  58,  32, 110, 111,  32,  85, 82,  76,
     32, 115, 112, 101,  99, 105, 102, 105, 101, 100, 33,  10,
     99, 117, 114, 108,  58,  32, 116, 114, 121,  32, 39,  99,
    117, 114, 108,  32,  45,  45, 104, 101, 108, 112, 39,  32,
    111, 114,  32,  39,  99, 117, 114, 108,  32,  45, 45, 109,
     97, 110, 117,  97, 108,  39,  32, 102, 111, 114, 32, 109,
    111, 114, 101,  32, 105, 110, 102, 111, 114, 109, 97, 116,
    105, 111, 110,  10
  ]
}

```

I've implemented my own function for automatic creation of users from AD and there I use self.storage.put which works just fine.

**Comment by mikeTWC1984** [comment]
Thanks for the report, I see the issue and will fix soon.

**Comment by mikeTWC1984** [comment]
OK, this is fixed on 1.5.8 release. However it doesn't let user link account to AD (works same way as original cronicle). Did you implement such functionality? You can send a PR, I'll take a look.

**Comment by tobyX** [comment]
I did something else, when the user cant be found on login I try an AD auth and if this one succeeds I create the user automatically with data pulled from AD.
You can take a look at my [draft](https://github.com/tobyX/cronicle-edge/blob/08091a83859e950355d4ef672e13d23dc2cce351/lib/user.js), some things are still hard coded and I will add configs for them also.

As we have multiple users and they shouldnt see the jobs from each other I plan to get also all AD groups for the user and assign them as categories to them (maybe even with ServerGroups, not sure about that yet). Categories will be automatically created if necessary, ServerGroups of course not. Unfortunately it looks as if I have to write the functions for creating of categories automatically myself as the existing functions validate if the user is allowed to do this?

**Comment by tobyX** [comment]
If you are interested in such a function I will gladly polish this up and send an PR!

**Comment by mikeTWC1984** [comment]
Yeah, ultimately cronicle should have some role systems (RBAC) that could be mapped to AD group and categories. There is a reporting tool called metabase, I like how they implemented this. 
Go ahead and submit a PR. Try to add AD group check. I think free account for all is not very practical for such tools, it should be limited by group.
