### ISSUE TITLE
Program crash with error 'Cannot find module octetstream.js'

### ISSUE THREAD

**Issue by s-z-a** [cronicle-edge/cronicle-edge#48]
Thanks for creating this version that is compatible with Windows! It's very helpful.
However, I'm having some issues keeping cronicle-edge running.

Cronicle-edge (version 1.6.1.1) is running on Windows Server as a Service using node-windows.

Issue:
After running well for a while (from half a day to a few days). The program will stop and the crash log will have the following log:

```
Error: Cannot find module 'E:\cronicle-edge-1.6.1.1\dist\bin\plugins\octetstream.js'
Require stack:
- E:\cronicle-edge-1.6.1.1\dist\bin\cronicle.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at E:\cronicle-edge-1.6.1.1\dist\bin\cronicle.js:71:4291
    at Array.forEach (<anonymous>)
    at new IncomingForm (E:\cronicle-edge-1.6.1.1\dist\bin\cronicle.js:71:4248)
    at formidable (E:\cronicle-edge-1.6.1.1\dist\bin\cronicle.js:71:15993)
    at Object.parseHTTPRequest (E:\cronicle-edge-1.6.1.1\dist\bin\cronicle.js:76:272)
    at E:\cronicle-edge-1.6.1.1\dist\bin\cronicle.js:65:9479
``` 

Could you kindly provide some directions on how to address and resolve this issue? Your assistance would be greatly appreciated. Thank you!

Also btw, if there's a new version available, what will be the best way to update the program for Windows?

**Comment by yusben** [comment]
I have the same error on Ubuntu in Docker container on version 1.6.1. It appeared today 4-5 times. The strange thing is that I deployed Cronicle 5-6 months ago and it has been working flawlessly since that time. If the error persists I will try to update to the latest version.

**Comment by mikeTWC1984** [comment]
@yusben  yeah, this is due to bundling, one of the dependencies (Formidable) has dynamic imports, so need to copy  some extra files to the bundle. That was fixes on latest release 
https://github.com/cronicle-edge/cronicle-edge/releases/tag/v.1.6.3
If you using containers you can use ghcr.io/cronicle-edge/cronicle-edge:1.6.3

@s-z-a Looks like I haven't added fix to the windows bundling script (will do soon), but to fix it copy files from node_modules/formidable/src/plugins/*.js to dist/bin/plugins

**Comment by mikeTWC1984** [comment]
@s-z-a, in general,  you'd need to run bundle script again for the desired release of this repo. Then overwrite dist/bin and dist/htdocs on your current installation using the freshly generated dist folder. Your data and configs will remain in old data/conf/queue folders (don't modify them). 
That shouldn't be hard to create some simple script for that. For now, you can do it manually (back up current dist folder before you begin).
