### ISSUE TITLE
Cannot read properties of undefined (reading 'log_file')]

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#77]
hi Mike,

Today I upgraded my cluster from 1.6.4 to 1.7.7. The update was flawless but after running some time I got 3 crashs on 2 to different workers. Both error messages are something like this:

```
[1708092450.796][2024-02-16 15:07:30][cronp03][1377][Error][error][crash][Emergency Shutdown: TypeError: Cannot read properties of undefined (reading 'log_file')][]
[1708093196.327][2024-02-16 15:19:56][cronp03][1255562][Error][error][crash][Emergency Shutdown: TypeError: Cannot read properties of undefined (reading 'log_file')][]
```
any idea what is going on?

**Comment by mikeTWC1984** [comment]
Is there any stack trace in the log, like on which line this error occured?

**Comment by dheise-rheinenergie-trading-com** [comment]
Hi Mike. I found someting in the Cronicle.log

```
Uncaught Exception: TypeError: Cannot read properties of undefined (reading 'log_file')][TypeError: Cannot read properties of undefined (reading 'log_file')
     at constructor.api_get_live_log_tail (/opt/cronicle/lib/api/job.js:134:24)
     at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:89:21)
     at WebServer.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/lib/request.js:484:12)
     at /opt/cronicle/node_modules/pixl-server-web/lib/request.js:416:10
     at wrapper (/opt/cronicle/node_modules/pixl-server-web/node_modules/async/dist/async.js:271:20)
     at replenish (/opt/cronicle/node_modules/pixl-server-web/node_modules/async/dist/async.js:441:29)
     at iterateeCallback (/opt/cronicle/node_modules/pixl-server-web/node_modules/async/dist/async.js:430:21)
     at /opt/cronicle/node_modules/pixl-server-web/node_modules/async/dist/async.js:327:20
     at /opt/cronicle/node_modules/pixl-server-web/lib/request.js:391:14
     at /opt/cronicle/lib/engine.js:131:5
```

log file excerpt:
```
[1708091784.563][2024-02-16 14:56:24][rtcronp02.gewkoelnag.de][2745451][Cronicle][debug][2][Startup complete, entering main loop][]
[1708092378.001][2024-02-16 15:06:18][rtcronp02.gewkoelnag.de][2745451][Cronicle][debug][1][Uncaught Exception: TypeError: Cannot read properties of undefined (reading 'log_file')][TypeError: Cannot read propert
ies of undefined (reading 'log_file')     at constructor.api_get_live_log_tail (/opt/cronicle/lib/api/job.js:134:24)     at constructor.handler (/opt/cronicle/node_modules/pixl-server-api/api.js:89:21)     at We
bServer.handleHTTPRequest (/opt/cronicle/node_modules/pixl-server-web/lib/request.js:484:12)     at /opt/cronicle/node_modules/pixl-server-web/lib/request.js:416:10     at wrapper (/opt/cronicle/node_modules/pix
l-server-web/node_modules/async/dist/async.js:271:20)     at replenish (/opt/cronicle/node_modules/pixl-server-web/node_modules/async/dist/async.js:441:29)     at iterateeCallback (/opt/cronicle/node_modules/pix
l-server-web/node_modules/async/dist/async.js:430:21)     at /opt/cronicle/node_modules/pixl-server-web/node_modules/async/dist/async.js:327:20     at /opt/cronicle/node_modules/pixl-server-web/lib/request.js:39
1:14     at /opt/cronicle/lib/engine.js:131:5]
[1708092378.001][2024-02-16 15:06:18][rtcronp02.gewkoelnag.de][2745451][Cronicle][debug][1][Emergency Shutdown: TypeError: Cannot read properties of undefined (reading 'log_file')][]
[1708092383.373][2024-02-16 15:06:23][rtcronp02.gewkoelnag.de][2790540][Cronicle][debug][2][Spawning background daemon process (PID 2790540 will exit)][["/opt/cronicle/nodejs/bin/node","/opt/cronicle/lib/main.js
"]]
[1708092383.602][2024-02-16 15:06:23][rtcronp02.gewkoelnag.de][2790547][Cronicle][debug][2][Cronicle v1.7.7 Starting Up][{"pid":2790547,"ppid":1,"node":"v20.11.0","arch":"x64","platform":"linux","argv":["/opt/cr
onicle/nodejs/bin/node","/opt/cronicle/lib/main.js"],"execArgv":[]}]
[1708092383.604][2024-02-16 15:06:23][rtcronp02.gewkoelnag.de][2790547][Cronicle][debug][2][Server IP: 10.24.2.52, Daemon PID: 2790547][]
[1708092383.711][2024-02-16 15:06:23][rtcronp02.gewkoelnag.de][2790547][Cronicle][debug][2][Startup complete, entering main loop][]
```

**Comment by mikeTWC1984** [comment]
ok, so the error comes from api_get_live_log_tail. I guess by some reason **params** has no log_file property


```js
	api_get_live_log_tail: function (args, callback) {

		const self = this;
		let params = Tools.mergeHashes(args.params, args.query);

		if (!this.requireParams(params, {
			id: /^\w+$/,
			auth: /^\w+$/
		}, callback)) return;

		if (params.auth != Tools.digestHex(params.id + self.server.config.get('secret_key'))) {
			return callback("403 Forbidden", {}, "Authentication failure.\n");
		}		

		let job = self.get_active_job_by_id(params.id)

		params.log_file= job.log_file
		params.event_title = job.event_title 
		params.hostname = job.hostname

		self.get_job_log_tail(params, callback)
	},
```

Not sure what the reason, maybe you call it from worker directly. Anyway, as a quick and dirty fix wrap params whti try/catch
```js
try {
		params.log_file= job.log_file
		params.event_title = job.event_title 
		params.hostname = job.hostname
} catch {
  
return callback("500", {}, "Missing parameters.\n");

}
```

or add log_file/event_title, hostname to requireParams

This will at least prevent cronicle crash while I investigating this.
I have been running v1.7.6 for many months, I havent seen this yet. But I only access UI from master node

**Comment by mikeTWC1984** [comment]
Hm, I did some changes on this function 6 months ago
https://github.com/cronicle-edge/cronicle-edge/commit/60ae05c89cb30fa13183b8e6da08015b4785849b

**Comment by mikeTWC1984** [comment]
Ahh, I guess this just not returning any value:
```self.get_active_job_by_id(params.id)```
maybe just do ```self.get_active_job_by_id(params.id) || {}``` for now to prevent crash

**Comment by mikeTWC1984** [comment]
OK, I guess that would be a proper fix:
```js
		let job = self.get_active_job_by_id(params.id)
		if(!job) {
			return callback("404 Not Found", {}, "Job is not active")
		}
```

I'll will do some testing and create a new release soon

**Comment by mikeTWC1984** [comment]
ok, just released 1.7.8, hopefully it should fix the problem

I did some review, I see there was job "null check" in api_get_live_log_tail, this is when user hit UI on manager node. Then it's routed to api_get_live_log_tail on the worker node (if needed), assuming job cannot be null. But in some cases job can get completed between those calls, so extra null checking is needed indeed. Thanks for catching it!

**Comment by dheise-rheinenergie-trading-com** [comment]
Hi Mike,

You are correct in assuming that I had opened the UI via a worker. 

I normally upgrade my cluster during operation and each server in turn. In between, I always check whether the nodes can start cleanly and execute jobs again.

My cluster is as follows:

server01: manager
server02: standby/backup manager
server03: pure worker

I always upgrade the servers from bottom to top (not the official way, I know ;-) but I need the cluster nearly 24-7):
1 upgrade server03
2 test UI and job execution server03
3 upgrade server02
4 test UI and job execution server02
5 switch Master from server01 to server02
6 upgrade server01
7 test UI and job execution server01
8 switch Master back from server02 to server01
9 finished

The errors occured in steps 2 and 4.

**Comment by dheise-rheinenergie-trading-com** [comment]
btw: I upgraded to 1.7.8. No further errors so far.
