### ISSUE TITLE
Can't seem to get sqlite3 working

### ISSUE THREAD

**Issue by danielangeloni** [cronicle-edge/cronicle-edge#92]
Hey there,

Either I am getting it all wrong but I can't seem to figure out how to get sqlite3 working.

I understand that we gotta run `npm i sqlite3` but I couldn't find a clean way to get this to run?

So I tried looking into editing the Dockerfile to include sqlite3
```
RUN ./bundle /dist --mysql --pgsql --s3 --lmdb --sqlite
```

But this didn't seem to do anything

Here is the error I get when running the container (invoking by `manager`)

```
Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- /opt/cronicle/bin/engines/SQL.js
- /opt/cronicle/bin/storage-cli.js
Error: Cannot find module 'sqlite3'
Require stack:
- /opt/cronicle/bin/engines/SQL.js
- /opt/cronicle/bin/storage-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at ko._driver (/opt/cronicle/bin/engines/SQL.js:37:40671)
    at ko.initializeDriver (/opt/cronicle/bin/engines/SQL.js:33:59178)
    at new Qo (/opt/cronicle/bin/engines/SQL.js:33:57832)
    at new ko (/opt/cronicle/bin/engines/SQL.js:37:40197)
    at lr (/opt/cronicle/bin/engines/SQL.js:1467:26478)
    at module.exports.setup (/opt/cronicle/bin/engines/SQL.js:1467:27510)
/opt/cronicle/bin/engines/SQL.js:36
${e.stack}`),new Error(`${t}
             ^

Error: Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- /opt/cronicle/bin/engines/SQL.js
- /opt/cronicle/bin/storage-cli.js
    at ko.initializeDriver (/opt/cronicle/bin/engines/SQL.js:36:14)
    at new Qo (/opt/cronicle/bin/engines/SQL.js:33:57832)
    at new ko (/opt/cronicle/bin/engines/SQL.js:37:40197)
    at lr (/opt/cronicle/bin/engines/SQL.js:1467:26478)
    at module.exports.setup (/opt/cronicle/bin/engines/SQL.js:1467:27510)
    at module.exports.startup (/opt/cronicle/bin/engines/SQL.js:1467:27447)
    at __construct.startup (/opt/cronicle/bin/storage-cli.js:58:4494)
    at /opt/cronicle/bin/storage-cli.js:58:19891
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v20.11.1
[1710847300.6][2024-03-19 07:21:40][manager1][9][Cronicle][debug][2][Cronicle v1.8.1 Starting Up][{"pid":9,"ppid":7,"node":"v20.11.1","arch":"arm64","platform":"linux","argv":["/usr/bin/node","/opt/cronicle/bin/cronicle.js","--echo","--foreground","--manager","--color","1"],"execArgv":[]}]
[1710847300.603][2024-03-19 07:21:40][manager1][9][Cronicle][debug][2][Server IP: 172.19.0.2, Daemon PID: 9][]
[1710847300.603][2024-03-19 07:21:40][manager1][9][Cronicle][debug][3][Starting component: Storage][]
[1710847300.604][2024-03-19 07:21:40][manager1][9][Storage][debug][5][Setting up storage system v3.1.16][]
[1710847300.684][2024-03-19 07:21:40][manager1][9][SQLEngine][debug][2][Setting up SQL Connection][{"client":"sqlite","table":"cronicle","useNullAsDefault":true,"connection":{"filename":"/tmp/cronicle.db"}}]
Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- /opt/cronicle/bin/engines/SQL.js
- /opt/cronicle/bin/cronicle.js
Error: Cannot find module 'sqlite3'
Require stack:
- /opt/cronicle/bin/engines/SQL.js
- /opt/cronicle/bin/cronicle.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at ko._driver (/opt/cronicle/bin/engines/SQL.js:37:40671)
    at ko.initializeDriver (/opt/cronicle/bin/engines/SQL.js:33:59178)
    at new Qo (/opt/cronicle/bin/engines/SQL.js:33:57832)
    at new ko (/opt/cronicle/bin/engines/SQL.js:37:40197)
    at lr (/opt/cronicle/bin/engines/SQL.js:1467:26478)
    at module.exports.setup (/opt/cronicle/bin/engines/SQL.js:1467:27510)
[1710847300.693][2024-03-19 07:21:40][manager1][9][Cronicle][debug][1][Uncaught Exception: Error: Knex: run $ npm install sqlite3 --save Cannot find module 'sqlite3' Require stack: - /opt/cronicle/bin/engines/SQL.js - /opt/cronicle/bin/cronicle.js][Error: Knex: run $ npm install sqlite3 --save Cannot find module 'sqlite3' Require stack: - /opt/cronicle/bin/engines/SQL.js - /opt/cronicle/bin/cronicle.js     at ko.initializeDriver (/opt/cronicle/bin/engines/SQL.js:36:14)     at new Qo (/opt/cronicle/bin/engines/SQL.js:33:57832)     at new ko (/opt/cronicle/bin/engines/SQL.js:37:40197)     at lr (/opt/cronicle/bin/engines/SQL.js:1467:26478)     at module.exports.setup (/opt/cronicle/bin/engines/SQL.js:1467:27510)     at module.exports.startup (/opt/cronicle/bin/engines/SQL.js:1467:27447)     at __construct.startup (/opt/cronicle/bin/cronicle.js:63:4519)     at /opt/cronicle/bin/cronicle.js:16:4300     at /opt/cronicle/bin/cronicle.js:2:18298     at replenish (/opt/cronicle/bin/cronicle.js:2:6947)]
Error: Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- /opt/cronicle/bin/engines/SQL.js
- /opt/cronicle/bin/cronicle.js
    at ko.initializeDriver (/opt/cronicle/bin/engines/SQL.js:36:14)
    at new Qo (/opt/cronicle/bin/engines/SQL.js:33:57832)
    at new ko (/opt/cronicle/bin/engines/SQL.js:37:40197)
    at lr (/opt/cronicle/bin/engines/SQL.js:1467:26478)
    at module.exports.setup (/opt/cronicle/bin/engines/SQL.js:1467:27510)
    at module.exports.startup (/opt/cronicle/bin/engines/SQL.js:1467:27447)
    at __construct.startup (/opt/cronicle/bin/cronicle.js:63:4519)
    at /opt/cronicle/bin/cronicle.js:16:4300
    at /opt/cronicle/bin/cronicle.js:2:18298
    at replenish (/opt/cronicle/bin/cronicle.js:2:6947)
```

**Comment by mikeTWC1984** [comment]
You need to install sqlite3 in the bundle folder ( dist ) not in the root. Some of the drivers include native dependencies that are typically not trivial to bundle with esbuild, so need to install on top of the bundle. So far I managed how to do it for leveldb, but lmdb and sqlite would require this extra step

**Comment by mikeTWC1984** [comment]
Although, after playing a bit. looks like you can just put native file (node_sqlite3.node) under dist/bin/build/ folder to make it work (plus also need to include sqlite3, currently it's marked as external dep).  I'll adjust bundle script on the next release

**Comment by danielangeloni** [comment]
ok cool thanks!!!
I couldn't figure it out. I'll give it another go next release 🙂

**Comment by mikeTWC1984** [comment]
> ok cool thanks!!! I couldn't figure it out. I'll give it another go next release 🙂

On the next release I'll just adjust the bundle script to copy binary. You still can set it up, just cd to dist folder and run "npm i sqlite3"

**Comment by danielangeloni** [comment]
I couldn't find a /dist folder when running an interactive shell on the built container.
I managed to get it working by editing the Dockerfile to be this (leaving the rest of it the same). Is this the best way for me to get it installed?
```
...
FROM cronicle/base-alpine as build
RUN apk add --no-cache npm 
COPY . /build
WORKDIR /build
RUN ./bundle /dist --mysql --pgsql --s3 --lmdb --sqlite
WORKDIR /dist
RUN npm i sqlite3

FROM cronicle/base-alpine 
...
```

**Comment by mikeTWC1984** [comment]
should work now
